# Generated by Django 5.0.4 on 2024-04-05 11:54

import builtins
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=50)),
                ('userEmail', models.EmailField(max_length=254)),
                ('userPassword', models.CharField(max_length=50)),
                ('userType', models.CharField(choices=[('Admin', 'Admin'), ('Project-Manager', 'Project-Manager'), ('Team-Leader', 'Team-Leader'), ('Employee', 'Employee')], max_length=100)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_Title', models.CharField(max_length=200)),
                ('projectName', models.CharField(max_length=50)),
                ('projectDescription', models.CharField(max_length=500)),
                ('projectStartDate', models.DateField(default=builtins.pow)),
                ('projectCreator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.customuser')),
            ],
        ),
    ]
